### ISSUE TITLE
russmaxdesign.github.io assets - fork under Intopia GitHub??

### ISSUE THREAD

**Issue by joe-watkins** [Intopia/developing2#18]
@russmaxdesign How would you feel about forking the awesome resource https://russmaxdesign.github.io/accessible-forms/ We could then set the Intopia fork to have an upstream remote and pull down changes when changes are made to the Primary repo. After that we could update links in training material. 

I know you've put a ton of work into this project - and not sure if you want to sell your soul, but would look better for branding/consistency. What ya think?

We'd just have to get in the habit of manually pulling down changes and pushing those in the Fork as I don't believe there is an automatic method for this - and probably shouldn't be.

**Comment by russmaxdesign** [comment]
As discussed, let's fork and adjust all references to the intopia version. We can decide on management of these two repos later.
