### ISSUE TITLE
Session 4: Downstream tweaks as a result of required vs. aria-required research

### ISSUE THREAD

**Issue by joe-watkins** [Intopia/developing2#24]
Session 4 > ARIA attributes that are no longer needed

Here we may be contradicting what we end up with in earlier sessions around the famous `required` vs. `aria-required` guidance.

/session04.html#/18/7 - /session04.html#/18/11

**Comment by russmaxdesign** [comment]
Resolved in recent PRs:

- #30 from Intopia/session4-remove-last-session 
- #29 from Intopia/adjust-aria-required 
- #31 from Intopia/add-disabled
